# Generated by Django 5.0.4 on 2024-12-01 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etkinlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
                ('aciklama', models.TextField()),
                ('tarih', models.DateField()),
                ('saat', models.TimeField()),
                ('sure', models.IntegerField()),
                ('konum', models.CharField(max_length=255)),
                ('kategori', models.CharField(max_length=100)),
                ('onay_durumu', models.CharField(default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kullanici_adi', models.CharField(max_length=30, unique=True)),
                ('sifre', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('konum', models.CharField(blank=True, max_length=255, null=True)),
                ('ilgi_alanlari', models.TextField(blank=True, null=True)),
                ('ad', models.CharField(max_length=30)),
                ('soyad', models.CharField(max_length=30)),
                ('dogum_tarihi', models.DateField(blank=True, null=True)),
                ('cinsiyet', models.CharField(blank=True, choices=[('Erkek', 'Erkek'), ('Kadın', 'Kadın')], max_length=10, null=True)),
                ('telefon_no', models.CharField(blank=True, max_length=15, null=True)),
                ('profil_fotografi', models.ImageField(blank=True, null=True, upload_to='profil_fotografi/')),
                ('is_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Katilimci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etkinlik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilk.etkinlik')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilk.kullanici')),
            ],
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='olusturan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ilk.kullanici'),
        ),
        migrations.CreateModel(
            name='BekleyenEtkinlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('aciklama', models.TextField()),
                ('tarih', models.DateField()),
                ('saat', models.TimeField()),
                ('sure', models.IntegerField()),
                ('konum', models.CharField(max_length=200)),
                ('kategori', models.CharField(max_length=100)),
                ('olusturan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ilk.kullanici')),
            ],
        ),
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metin', models.TextField()),
                ('gonderim_zamani', models.DateTimeField(auto_now_add=True)),
                ('etkinlik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesajlar', to='ilk.etkinlik')),
                ('gonderici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gonderilen_mesajlar', to='ilk.kullanici')),
            ],
        ),
        migrations.CreateModel(
            name='Puan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puan', models.IntegerField()),
                ('kazanilan_tarih', models.DateField()),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ilk.kullanici')),
            ],
        ),
    ]
